using System;
using System.Linq;
using Newtonsoft.Json;
using YourBuddy;

int checks = 0;
void Check(bool condition, string name)
{
    if (!condition) throw new InvalidOperationException(name);
    checks++;
}
ResourceDutySettings settings = new();
for (int kind = 0; kind < 3; kind++)
{
    ResourceRule rule = settings.Rule(kind);
    string name = ResourceDutySettings.Label(kind);
    Check(!rule.Enabled && !rule.Buy, name + " defaults off");
    settings.Edit($"resources {name} on");
    Check(rule.Enabled, name + " enables");
    Check(rule.NeedsRefill(29.9f, false), "starts below threshold");
    Check(rule.NeedsRefill(30, false), "starts at threshold");
    Check(rule.NeedsRefill(65, true), "continues above start until target");
    Check(!rule.NeedsRefill(80, true), "stops at target");
    Check(!rule.NeedsRefill(float.NaN, true), "invalid reading cannot run");
    settings.Edit($"resources {name} start 80");
    settings.Edit($"resources {name} target 30");
    settings.Edit($"resources {name} target 101");
    settings.Edit($"resources {name} start -1");
    settings.Edit($"resources {name} start 2147483648");
    Check(rule.Start == 30 && rule.Target == 80, "reject invalid thresholds without mutation");
    settings.Edit($"resources {name} start 40");
    settings.Edit($"resources {name} target 90");
    Check(rule.Start == 40 && rule.Target == 90, "custom thresholds");
    settings.Edit($"resources {name} buy on");
    Check(rule.Buy, "purchase opt-in");
    settings.Edit($"resources {name} off");
    Check(!rule.NeedsRefill(10, true), "disabling cancels pending demand");
    settings.Edit($"resources {name} on");
}
settings.Edit("resources budget 500");
settings.Edit("resources reserve 100");
ResourceRule oxygen = settings.Oxygen;
Check(settings.CanBuy(oxygen, 500, 600), "exact allowance and reserve allowed");
Check(!settings.CanBuy(oxygen, 501, 1000), "cannot exceed allowance");
Check(!settings.CanBuy(oxygen, 500, 599), "cannot dip below reserve");
Check(!settings.CanBuy(oxygen, 0, 1000) && !settings.CanBuy(oxygen, -1, 1000), "invalid prices rejected");
Check(!settings.CanBuy(oxygen, 1, int.MinValue), "cash arithmetic cannot wrap");
settings.Edit("resources pause");
Check(!settings.CanBuy(oxygen, 1, 1000), "pause prevents spending");
settings.Edit("resources resume");
Check(settings.CanBuy(oxygen, 1, 1000) && settings.Budget == 500, "resume preserves allowance");
settings.Edit("resources oxygen buy off");
Check(!settings.CanBuy(oxygen, 1, 1000), "separate purchase permission");
settings.Edit("resources oxygen buy on");
settings.Edit("resources budget -1");
settings.Edit("resources budget 2147483648");
Check(settings.Budget == 500, "invalid budgets cannot change allowance");
settings.Budget -= 200;
string json = JsonConvert.SerializeObject(settings);
ResourceDutySettings loaded = JsonConvert.DeserializeObject<ResourceDutySettings>(json) ?? throw new Exception("no settings");
loaded.Normalize();
Check(loaded.Budget == 300 && loaded.Reserve == 100, "spent allowance survives game serializer roundtrip");
Check(loaded.Fuel.Enabled && loaded.Energy.Buy && loaded.Oxygen.Start == 40, "all rules survive save");
ResourceDutySettings old = JsonConvert.DeserializeObject<ResourceDutySettings>("{}") ?? throw new Exception("no defaults");
old.Normalize();
Check(!old.Oxygen.Enabled && old.Budget == 0, "old save defaults disabled");
ResourceDutySettings damaged = JsonConvert.DeserializeObject<ResourceDutySettings>(
    "{\"Oxygen\":null,\"Fuel\":{\"Enabled\":true,\"Buy\":true,\"Start\":95,\"Target\":20},\"Budget\":-10}") ?? throw new Exception("no damaged settings");
damaged.Normalize();
Check(!damaged.Oxygen.Enabled && !damaged.Fuel.Enabled && !damaged.Fuel.Buy && damaged.Budget == 0, "malformed saves fail closed");
ResourceDutyMenu menu = new();
Check(menu.Commands(new[] { "Status" }).SequenceEqual(new[] { "Status" }), "resource wrapper does not inject submenu shortcuts");
Check(menu.Answer("follow me") == null, "ordinary orders fall through");
Check(menu.Answer("resources") != null && menu.Commands([]).Contains("Oxygen"), "resource overview controls");
menu.Answer("resources oxygen refill");
Check(menu.Commands([]).Contains("Start: 30%"), "exact threshold button");
menu.Answer("Start: 30%");
Check(ResourceDuty.Settings.Oxygen.Start == 30, "clicking threshold only opens input");
Check(menu.Answer("101")!.StartsWith("Use", StringComparison.Ordinal), "invalid percentage retains editor");
menu.Answer("35%");
Check(ResourceDuty.Settings.Oxygen.Start == 35, "menu edits live policy");
Check(menu.Answer("resources oxygen start invalid") != null && ResourceDuty.Settings.Oxygen.Start == 35,
    "invalid settings consumed without falling through to ordinary actions");
menu.Answer("resources\toxygen\ton");
Check(ResourceDuty.Settings.Oxygen.Enabled, "whitespace cannot misroute resource command");
menu.Answer("resources back");
Check(menu.Commands(new[] { "Status" }).First() == "Status", "back restores ordinary controls");
menu.Answer("resources energy stock");
Check(menu.Commands([]).All(label => label.Length <= 13), "resource labels fit compact columns");
menu.Answer("Allow buying");
Check(ResourceDuty.Settings.Energy.Buy && !ResourceDuty.Settings.Fuel.Buy, "short label changes selected resource only");
menu.Reset();
Check(menu.Answer("Allow buying") == null, "closed resource menu cannot dispatch stale labels");
Check(menu.Commands(new[] { "Status" }).Count == 1, "closing dialog resets submenu");
menu.Answer("resources oxygen stock");
menu.Commands([]);
menu.Answer("Stock < 1");
menu.Answer("2");
menu.Commands([]);
menu.Answer("Buy up to 1");
menu.Answer("3");
Check(ResourceDuty.Settings.Oxygen.MinCells == 2 && ResourceDuty.Settings.Oxygen.BuyQuantity == 3, "click and type stock/quantity");
menu.Answer("resources oxygen refill");
menu.Commands([]);
menu.Answer("Start: 35%");
menu.Answer("cancel");
Check(ResourceDuty.Settings.Oxygen.Start == 35, "cancel preserves percentage");
menu.Commands([]);
menu.Answer("Start: 35%");
menu.Answer("1");
Check(ResourceDuty.Settings.Oxygen.Start == 1, "one percent accepted");
menu.Commands([]);
menu.Answer("Start: 1%");
menu.Answer("50");
Check(ResourceDuty.Settings.Oxygen.Start == 50, "fifty percent accepted");
settings.Edit("resources oxygen stock 2");
settings.Edit("resources oxygen quantity 3");
Check(settings.Oxygen.MinCells == 2 && settings.Oxygen.BuyQuantity == 3, "typed restock settings");
settings.Edit("resources oxygen quantity 0");
settings.Edit("resources oxygen stock 101");
Check(settings.Oxygen.MinCells == 2 && settings.Oxygen.BuyQuantity == 3, "invalid stock counts rejected");
settings.Budget = 500;
Check(settings.AffordableQuantity(oxygen, 100, 350, 5) == 2, "partial batch respects wallet reserve");
Check(settings.AffordableQuantity(oxygen, 200, 1000, 5) == 2, "partial batch respects shared allowance");
Check(settings.AffordableQuantity(oxygen, 100, 1000, 1) == 1, "never exceed requested quantity");
Check(settings.AffordableQuantity(oxygen, 100, 199, 5) == 0, "cannot afford a single cell");
Check(settings.AffordableQuantity(oxygen, 0, 1000, 5) == 0, "invalid price cannot divide by zero");
ResourceDutySettings restoredStock = JsonConvert.DeserializeObject<ResourceDutySettings>(JsonConvert.SerializeObject(settings)) ?? throw new Exception("no restock settings");
Check(restoredStock.Oxygen.MinCells == 2 && restoredStock.Oxygen.BuyQuantity == 3, "restock controls persist");
BuddyCommandMenu groups = new();
string[] available = ["Follow", "Stay", "Goto", "Tidy", "Fetch suit", "Inside"];
Check(groups.Commands(available).Contains("Movement") && !groups.Commands(available).Contains("Follow"), "root groups commands");
groups.Answer("Movement");
Check(groups.Commands(available).Contains("Follow") && !groups.Commands(available).Contains("Tidy"), "movement excludes jobs");
groups.Answer("Jobs");
Check(groups.Commands(available).SequenceEqual(new[] { "Tidy", "Main menu" }), "jobs respect context availability");
groups.Answer("Suit & travel");
Check(!groups.Commands(available).Contains("Unsuit"), "unsuited action remains filtered");
groups.Reset();
Check(groups.Commands(available).Contains("Resources"), "closing resets grouped menu");
Check(groups.Answer("follow me") == null, "typed orders keep existing parser");
menu.Reset();
foreach (string page in new[] { "Movement", "Jobs", "Suit & travel" })
{
    groups.Answer(page);
    Check(!menu.Commands(groups.Commands(available)).Contains("Resources"), page + " does not repeat Resources");
}
groups.Reset();
Check(menu.Commands(groups.Commands(available)).Count(x => x == "Resources") == 1, "root contains Resources once");
int starts = 0;
ResourceDutyMenu startMenu = new(() => { starts++; return "requested"; }, () => "holding an order");
startMenu.Answer("resources");
startMenu.Commands([]);
Check(startMenu.Answer("Start duties") == "requested" && starts == 1, "start duties dispatches explicit action once");
Check(startMenu.Answer("resources state")!.Contains("holding an order", StringComparison.Ordinal), "readiness appears in status");
startMenu.Answer("resources oxygen");
Check(startMenu.Commands([]).Contains("Refilling") && startMenu.Commands([]).Contains("Restocking"), "separate resource sections");
Check(!startMenu.Commands([]).Any(x => x.StartsWith("Start:", StringComparison.Ordinal)), "overview omits detailed fields");
ErrandCooldown cooldown = new();
Check(cooldown.Ready(0), "new errands may run");
cooldown.Hold(10, 120);
Check(!cooldown.Ready(11) && !cooldown.Ready(129), "failed errands cannot win during retry delay");
cooldown.Hold(20, 5);
Check(!cooldown.Ready(129) && cooldown.Ready(130), "shorter retries cannot shorten an existing hold");
cooldown.Hold(130, 60);
Check(!cooldown.Ready(189) && cooldown.Ready(190), "a later failure creates a fresh hold");
// Exercise the menu-to-parser handoff with the merged production command parser.
BuddyBehaviour buddy = new() { Floating = false, SuitSuited = false, IsDead = false, Asleep = false, Hiding = false, ReachDescription = null };
ResourceDutyMenu resourceMenu = new();
BuddyCommandMenu orderMenu = new();
string Answer(string text) => resourceMenu.Answer(text) ?? orderMenu.Answer(text) ?? BuddyDialogCommands.Run(buddy, text);
Answer("Jobs");
Check(orderMenu.Commands(BuddyDialogCommands.NamesFor(buddy)).SequenceEqual(new[] { "Tidy", "Sell", "Snack", "Play", "Main menu" }),
    "merged job menu exposes supported actions only");
Answer("start cleaning");
Check(buddy.LastOrder == "tidy", "inflected orders pass through grouped menus");
Answer("resources oxygen refill");
resourceMenu.Commands([]);
Answer("Start: 50%");
string edited = Answer("25%");
Check(ResourceDuty.Settings.Oxygen.Start == 25 && !edited.StartsWith("code:", StringComparison.Ordinal) && buddy.LastOrder == "tidy",
    "resource percentage never dispatches password or ordinary order");
Answer("resources back");
Answer("get some snacks");
Check(buddy.LastOrder == "snack", "resource exit restores inflected ordinary commands");
Answer("do not follow me");
Check(buddy.LastOrder == "snack", "negated request remains inert after resource editing");
Answer("keep following me");
Check(buddy.LastOrder == "follow", "following suffix survives menu integration");
Answer("stop following");
Check(buddy.LastOrder == "stay", "stop following retains precedence");
buddy.IsOutside = true;
Check(orderMenu.Commands(BuddyDialogCommands.NamesFor(buddy)).SequenceEqual(new[] { "Main menu" }),
    "grouped jobs remain unavailable outside");
Console.WriteLine($"Passed {checks} resource policy, menu and persistence checks.");
